sudo: false

env:
  - JACOCO_VERSION=0.7.4.201502262128
  - GITHUB_USER=cyChop
  - GITHUB_REPO=maths-java

language: java

jdk:
  - oraclejdk8

before_script:
  - "mvn clean install"

script
  - "mvn org.jacoco:jacoco-maven-plugin:$JACOCO_VERSION:prepare-agent install"

after_success:
  - "mvn org.jacoco:jacoco-maven-plugin:$JACOCO_VERSION:report org.eluder.coveralls:coveralls-maven-plugin:report"
  - "[[ $TRAVIS_REPO_SLUG == $GITHUB_USER/$GITHUB_REPO ]] && [[ $TRAVIS_BRANCH == quality ]] && mvn sonar:sonar"
  