sudo: false

env:
  - JACOCO_VERSION=0.7.4.201502262128

language: java

jdk:
  - oraclejdk8

before_script:
  - "mvn clean install"

script
  - "mvn org.jacoco:jacoco-maven-plugin:$JACOCO_VERSION:prepare-agent install"

after_success:
  - "mvn org.jacoco:jacoco-maven-plugin:$JACOCO_VERSION:report org.eluder.coveralls:coveralls-maven-plugin:report"
  - "[[ $TRAVIS_PULL_REQUEST == false ]] && [[ $TRAVIS_BRANCH == quality ]] && mvn sonar:sonar"
  